# Generated by Django 3.0 on 2019-12-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter1', models.CharField(max_length=10)),
                ('parameter2', models.CharField(max_length=10)),
                ('parameter3', models.CharField(max_length=10)),
                ('parameter4', models.CharField(max_length=10)),
                ('parameter5', models.CharField(max_length=10)),
                ('parameter6', models.CharField(max_length=10)),
                ('parameter7', models.CharField(max_length=10)),
                ('parameter8', models.CharField(max_length=10)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
            ],
        ),
    ]
